DROP DATABASE IF EXISTS passcode;
CREATE DATABASE passcode;

USE passcode;

DROP TABLE IF EXISTS easy;
CREATE TABLE easy (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(10) NOT NULL,
  score INT NOT NULL
);

DROP TABLE IF EXISTS medium;
CREATE TABLE medium (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(10) NOT NULL,
  score INT NOT NULL
);

DROP TABLE IF EXISTS hard;
CREATE TABLE hard (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(10) NOT NULL,
  score INT NOT NULL
);
